### ISSUE TITLE
Map doesn't reflect the latest coordinates of an area

### ISSUE THREAD

**Issue by heliodor** [OpenBeta/open-tacos#1095]
I updated the coordinates for an area and the map hasn't been updated (even minutes later).

Tried it for two more sub-areas and the same problem.

Or maybe it's a shortcoming of the current design but from the user's point of view, it's a bug.

**Comment by heliodor** [comment]
Example: click the link with the coordinates and compare to the map at the bottom of the page:
https://openbeta.io/area/cb5ef655-d4ad-576a-9acc-7ba2a83fefb3/la-escalera

**Comment by vnugent** [comment]
Pending backend [PR 391](https://github.com/OpenBeta/openbeta-graphql/pull/391) will update the maptiles as frequently as possible.  

FYI in recent backend changes only coordinates of **leaf** (aka "crag") areas are used to calculate their parent's bounding boxes and the polygon since it doesn't make sense for a large area to have a single point.  

- https://github.com/OpenBeta/open-tacos/issues/1057
- https://github.com/OpenBeta/open-tacos/issues/1055
- https://github.com/OpenBeta/open-tacos/issues/1078

The area edit page needs to disable/enable coordinates edit based on the isLeaf attribute.

**Comment by heliodor** [comment]
To add some nuance to the coordinates of an area:

It makes sense to put the coordinates of a crag on the parking lot, not the actual rock. It fits my mental model: If I'm at home and I think of heading to ABC crag, I'm thinking of the parking lot, not a particular rock. When I think of going to a sector, I'm thinking of the actual rock.

But really, this is making up for the lack of certain details for the area. Maybe areas should have one or more "arrival points" with coordinates. Or even more detailed fields. Consider incorporating all approach trails into the bounding box for the area.

**Comment by vnugent** [comment]
The maptiles exporter job now runs every 2 hrs (can be adjusted as needed).   I'll  submit a new PR for enabling/disabling area coordinates input when it makes sense.

Please continue the finer-grained area metadata discussion here: https://github.com/OpenBeta/open-tacos/issues/1101

**Comment by vnugent** [comment]
Fixed in https://github.com/OpenBeta/openbeta-graphql/pull/391 and #1102
