### ISSUE TITLE
Recently added climb is not allowing me to tick climb (occurring across multiple climbs)

### ISSUE THREAD

**Issue by emilyg1709** [OpenBeta/open-tacos#1130]
## Steps to Reproduce

1. Go to Hercules Hug in Washington state
2. attempt to tick climb
3. "cannot fetch climb grade" error appears, no tick is made

## Expected Behavior

should tick like any other boulder

## Current Behavior

does not tick climb and receive error message that grade can't be retrieved

## Browser & version
<---  Example: Firefox 102.7.0esr  -->
google chrome

## Operating system
<--- Example:  MacOS 13.2.1 -->
windows

**Comment by daneashman** [comment]
I seem to be running into the same issue.

Here is a screenshot of what I'm seeing:
<img width="473" alt="Screenshot 2024-07-24 at 5 07 26 PM" src="https://github.com/user-attachments/assets/d82c9ce8-bfc8-46d7-ac2e-a0c097b0f0f3">

I pulled the climb using GraphQL and noticed `data.yds` was `null`, but `data.grades.yds` was set correctly. (See examples below)

From querying other climbs that do not have this error (e.g. Levitate in Smith Rock - also shown below), I noticed that both the `data.yds` and `data.grades.yds` were populated.

My guess is that when creating or editing a climb, the grade is posted to `data.grades.yds` but not `data.yds` for some reason. Futhermore, when creating a tick, it is likely trying to pull a value from `data.yds`, and because it is `null`, we get an error.

Issue #1165 might be due to the same behaviour. 

Any further help with this would be greatly appreciated!

### Examples:

Climb with the issue:
```json
{
  "data": {
    "climb": {
      "yds": null,
      "uuid": "e78cb4d4-fca0-4902-b445-b66465e7882b",
      "safety": null,
      "id": "e78cb4d4-fca0-4902-b445-b66465e7882b",
      "gradeContext": "US",
      "name": "Victory Whip",
      "grades": {
        "brazilianCrux": null,
        "ewbank": null,
        "font": null,
        "french": null,
        "uiaa": null,
        "vscale": null,
        "yds": "5.11a"
      },
      "parent": {
        "id": "64140d49f0cf0083295f4b38",
        "areaName": "Pipeline Wall"
      }
    }
  }
}
```

Climb without the Issue:
```json
{
  "data": {
    "climb": {
      "yds": "5.12a",
      "uuid": "fa9433f3-5fc9-5da2-a209-12ea76c01586",
      "safety": "UNSPECIFIED",
      "id": "fa9433f3-5fc9-5da2-a209-12ea76c01586",
      "gradeContext": null,
      "name": "Levitate",
      "grades": {
        "brazilianCrux": null,
        "ewbank": null,
        "font": null,
        "french": "7a+",
        "uiaa": null,
        "vscale": null,
        "yds": "5.12a"
      },
      "parent": {
        "id": "6368a36ae80bff5a99582948",
        "areaName": "(4) Star Wall"
      }
    }
  }
}
```

**Comment by AStonedApe** [comment]
This is happening to me too. Can't tick anything (so far, I'll keep trying). Getting the same "cannot fetch climb grade" error.

![Screenshot from 2024-09-15 21-32-46](https://github.com/user-attachments/assets/68f093cb-83e8-418d-98d2-11196d53023e)

**Comment by julianlam** [comment]
@vnugent I'd like to take a look at this issue, can you please email me the API keys to get set up for auth?

**Comment by julianlam** [comment]
I'm attempting to debug this, but first I need to find a climb on the staging database that exhibits this problem. The ones mentioned on this issue (_Hercules Hug_ and _Victory Whip_) are not on staging, while _Levitate_ does, but does not exhibit this issue.

**Comment by musoke** [comment]
What if you create a new route on staging?

**Comment by julianlam** [comment]
@musoke Perfect. Reproduced.

**Comment by julianlam** [comment]
I have created PR #1193 to resolve this issue. As @daneashman suggested, it was related to use of the now-deprecated `yds` property in the climb. It was replaced with the `Grade` object but the `TickButton` component, which supplied the grade to the `TickForm` component, was still sending in `yds`, which is `null` on climbs created since the deprecation.
