### ISSUE TITLE
New user flow needs some TLC

### ISSUE THREAD

**Issue by julianlam** [OpenBeta/open-tacos#1192]
## Steps to Reproduce

1. Register a new account via OAuth
2. Login flow returns me to previous page (index)
3. Redirected to `/account/changeUsername`

## Expected Behavior

One of:

1. Random username chosen to simplify onboarding
2. Modal or other informative element instructing user to choose a new username

## Current Behavior

* Constant redirects to `changeUsername` without further instruction

**Comment by musoke** [comment]
I get occasional redirects to change username even as an old user.  I have already changed my username.

**Comment by clintonlunn** [comment]
The issue seems to be that the frontend does a check for if there is a username in the db even though we always generate at least a randomized username. On the first login we need to insert the user profile into the database through Auth0


remove the requirement to change username when one is already auto assigned through auth0 (OnboardingCheck component) 
test - create new account in auth0 and when it's not in the db


steps we might need to take to help fix this:

- update database from auth0 action
- get jwt token from auth0 and send to the api and then call the updateUsername to send username directly to backend - https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens
- remove `<OnboardingCheck isAppDir={false} />`(which all it does it looks to see if you have a profile in the db). `_app.tsx`, `/(default)/layout.tsx`

**Comment by vnugent** [comment]
Fixed in #1224 and #1125.
