### ISSUE TITLE
Debounce request to Typesense and Mapbox api

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#168]
- Implement a debouncer function to reduce API calls.  More info: https://www.algolia.com/doc/ui-libraries/autocomplete/guides/debouncing-sources/
- maybe don't send the request until the user has typed at least 3 letters

search widget code:  https://github.com/OpenBeta/open-tacos/tree/nextjs/src/components/search

To do:
1.  Create a new debounce promise function ([sample code](https://www.algolia.com/doc/ui-libraries/autocomplete/guides/debouncing-sources/#writing-an-asynchronous-debouncing-function))
2. ~~Wrap `getAlgoliaResults()` [function](https://github.com/OpenBeta/open-tacos/blob/nextjs/src/components/search/ClimbSearch.tsx#L22) with the new debouncer function~~

**Comment by clintonlunn** [comment]
I'm not totally sure if I understand what I'm looking at, but it looks like some portions of this issue might be out of date. It does not seem that getAlgoliaResults() is present in this project anymore, and has since been replaced with the typesense client? 

It looks like the <Autocomplete> component is used in the [CragFinder](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/search/CragFinder.tsx#L33) and [ClimbSearchByName](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/search/ClimbSearchByName.tsx)

There is a check within the CragFinder to not search unless the user inputs > 3 characters, but that check is not present in ClimbSearchByName.

**Comment by vnugent** [comment]
@clintonlunn  You're right.  We've replaced Algolia with Typesense.  Can you implement an async debouncer that can be used for both Typesense API and the Mapbox geocoding API?

**Comment by clintonlunn** [comment]
@vnugent Sure, I'll give it a go!
