### ISSUE TITLE
Allow users to import previous ticks from Mountain Project

### ISSUE THREAD

**Issue by Downster** [OpenBeta/open-tacos#447]
For ease of use for our users, allow the user to import their previously ticked climbs from mountain project. They will be prompted to do so on both their profile page and the climbs page by a modal/notification which can be disabled by ticking a checkbox. The ticked climbs will be stored as an array of climb Id's in the user-meta-data.

**Comment by vnugent** [comment]
FYI - code to fetch user ticklist: https://gitlab.com/openbeta/mp-pyramid-backend/-/tree/initial/app/Controllers/Http

Notes:
- You can't run the above code directly on the frontend due to CORS restriction
- Instead put the code in an API endpoint [example here](https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/api/user/exists.ts), and then call it from the frontend

**Comment by Downster** [comment]
Awesome, thanks for that. Also, as far as I can tell there is no correlation between the mountain project climb-id's and the open-beta climb-id's unless I missed something. I've been trying to figure out a way to query our climbs and do a comparison so I can grab the open taco UUIDs of the climbs. Any insight into which direction I should take this?

**Comment by vnugent** [comment]
tacos id from mp id: https://github.com/OpenBeta/openbeta-graphql/blob/develop/src/db/import/ClimbTransformer.ts#L14

Edit:
You don't need the muuid part.  This should work:

```javascript
import { v5 as uuidv5, NIL } from 'uuid'

const mpId = '123445'
const tacosId = uuidv5(mpId, NIL)

```

**Comment by Downster** [comment]
Completed
