### ISSUE TITLE
Change login method to email & password

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#464]
Email viet at openbeta.io for Auth0 credential.
- [x] Update Auth0 test tenant and tested
- [x] Update prod tenant (in progress)
- [x] Migrate account with photos (in progress)

**Comment by JetseVerschuren** [comment]
After looking into it, and testing on the dev tenant, these below steps should convert the app into username-password only. I tried to allow both passwordless and with password, but due to some auth0 limitations that seems to be impossible. It's also necessary to manually transfer metadata from the passwordless accounts to the new password accounts. By default they're separate in auth0. It's possible to automatically merge them when a new account with the same email is created, but the official plugin doesn't work with passwordless, and the alternatives would require a lot of extra logic and UI in our app (which I really didn't want to do :sweat_smile:).

Applications -> Applications -> Tacos -> Connections -> username-password = on
Authentication -> Database -> Username-Password-Authentication -> Requires username = off
Branding -> universal login -> advanced -> login -> customize (html) = off
Applications -> Applications -> Tacos -> Connections -> email = off

Then every existing user has to re-register (with the same email, so migration is easier), and you have to manually transfer the metadata

**Comment by vnugent** [comment]
@all-contributors add @JetseVerschuren for code and ideas

**Comment by vnugent** [comment]
@JetseVerschuren Thanks for this.  I've completed the migration in production. (copying user metadata over to their new account)  

Users will have to set a new password.

---
<img width="521" alt="Screen Shot 2022-10-01 at 5 25 38 PM" src="https://user-images.githubusercontent.com/3805254/193416564-739edc0c-f793-4e47-aacb-41786a9df252.png">
