### ISSUE TITLE
Profile Page: Difficult to see tagged climb name depending on the image

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#644]
## Expected Behavior
The user should be able to clearly read the tagged climb name when viewing on desktop.

## Current Behavior
Depending on the color of the background, the climb name tag inside of the image is difficult to read.
![image](https://user-images.githubusercontent.com/24685932/210918306-32084202-ea8f-495c-88e1-8aac6f1957ff.png)
The mobile version does not have this issue because the images are displayed slightly differently.
![image](https://user-images.githubusercontent.com/24685932/210916730-1d90f102-1b70-49e7-b03d-5fa53c703fa7.png)

## Possible Solution
1. We could copy the same or similar style from the `+ new tag` button below it. See example:
![image](https://user-images.githubusercontent.com/24685932/210917156-d74611f0-f42a-4ce4-bf49-744606049384.png)

3. Put a background color behind the tag area (but what would happen if there were multiple tags per photo like would in a zoomed out shot of a whole area). it can be more transparent than this unhovered
![image](https://user-images.githubusercontent.com/24685932/210918119-f511f6ba-bc68-4252-8aa5-ea8b15b015b1.png)

## Steps to Reproduce

1. Navigate to user profile 
2. observe images (note. user must have uploaded images and tagged climbs in images)

## Context (Environment)
As a user I am trying to read the tagged climb of a picutre.

**Comment by clintonlunn** [comment]
@vnugent I'm forgetting what we decided on for this issue. Do you have a preference?

**Comment by vnugent** [comment]
I don't think we decided anything yet.

On desktop I'd prefer a clean and minimalist look without showing any tags/button.  When a photo piques your interest you can hover over it to see tag(s) or if you're the owner you can create new tags.  We can darken the photo on hover so that tags and buttons are more readable.

Similar to an [art gallery wall](https://www.moma.org/collection/about/curatorial-departments/photography) in real life, placards are typically very small and sometime placed discretely at a corner, far away from the artworks.    

IG is a good example:

https://www.instagram.com/openbetaproject/

<img width="1011" alt="Screen Shot 2023-01-14 at 1 01 46 PM" src="https://user-images.githubusercontent.com/3805254/212470794-2a9554dc-bb2f-424b-b204-9a263e9bbf0c.png">

**Comment by clintonlunn** [comment]
[Screencast from 01-16-2023 01:11:04 PM.webm](https://user-images.githubusercontent.com/24685932/212766280-5825a11d-1761-4267-84a0-3afa85fd8759.webm)
@vnugent what do you think about something like this? 


In addition to that we should probably separate the hover events so we don't hover on all images at once.

**Comment by vnugent** [comment]
> Screencast from 01-16-2023 01:11:04 PM.webm

Yes, that should work. Thanks.
