### ISSUE TITLE
Username Validation Incorrect Warning

### ISSUE THREAD

**Issue by dan-kat-dev** [OpenBeta/open-tacos#718]
This issue tracker is **ONLY** used for reporting bugs!

## Expected Behavior

When editing your profile user name, you get an error when there are spaces in the user name. The warning message should probably say 'username cannot contain spaces' or something.

## Current Behavior

![image](https://user-images.githubusercontent.com/62715496/222917613-66356a00-506e-4dda-8970-5782370c8bd1.png)
The actual error message says 'Must start and end with a letter or number' which I think is incorrect

## Possible Solution

Show correct user name validation warning, maybe something like "User name cannot contain spaces" or "User name must contain only letters and numbers"

**Comment by vnugent** [comment]
@daniel-n-kaye thank you for suggesting this!

@all-contributors add @daniel-n-kaye for idea

**Comment by dan-kat-dev** [comment]
@vnugent I'd be willing to try to take this on as a first issue, if that's ok, as it seems like it would hopefully be a pretty isolated update.

**Comment by vnugent** [comment]
The error messages are listed here

https://github.com/OpenBeta/open-tacos/blob/6f08aa18892fb7fbf730129030b40a2c67184e33/src/components/users/account/ProfileEditForm.tsx#L18

Since profile update code requires authentication with Auth0, please send an email: viet at openbeta dot io and I'll reply with some additional API keys for the dev environment.

**Comment by shoaib-31** [comment]
@vnugent I think my pull request will do the work.

**Comment by hawkishpolicy** [comment]
Is this still active?

**Comment by clintonlunn** [comment]
This is still an active issue. @danekshea any updates on your changes?

**Comment by vnugent** [comment]
I'm working on moving some of user profile functionality to our own DB.  Username update is the first piece so I can take on this issue.  What do you all think the error message should be?

Username validation rules:
1.  cannot contain spaces or special characters
2. must begin with a letter

See https://github.com/OpenBeta/open-tacos/issues/830

**Comment by hawkishpolicy** [comment]
Based on my understanding of the regex, it appears that it requires a username to begin and end with a letter or number.

It cannot contain spaces but it can contain "." or "-" or "_" 

Would these be considered special characters?

I was brainstorming on how best to write this error message so that users can understand it clearly.

What about:

1. Must begin and end with a letter or number.
2. Can contain "." or "-" or "_"
3. Cannot contain spaces.

It's verbose but it is specific. 

@zichongkao had some ideas. 

That might be a long error message....we could break the regex into components so that it would trip each test as the User tried their new nickname.

**Comment by vnugent** [comment]
> Would these be considered special characters?

dot and underscore are allowed (but not as the first character)

**Comment by hawkishpolicy** [comment]
I'm okay with it.
