### ISSUE TITLE
Prevent Test Area photos from showing on the front page

### ISSUE THREAD

**Issue by zichongkao** [OpenBeta/open-tacos#835]
## Steps to Reproduce
It's hard to reproduce deterministically because the front page photos are randomly selected.

## Screenshots
Look at the first image here:
<img width="1432" alt="image" src="https://github.com/OpenBeta/open-tacos/assets/3641356/67d70c15-4255-4d63-af4e-3cc564f3f197">

## Expected Behavior
Test area (https://openbeta.io/crag/18c5dd5c-8186-50b6-8a60-ae2948c548d1) photos should not show up in the front page. 

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

## Operating system
<--- Example:  MacOS 13.2.1 -->

**Comment by vnugent** [comment]
A coding challenge!

Use Array.`reducer()` function to exclude media objects whose `entityTags` array has an element with `targetId === '18c5dd5c-8186-50b6-8a60-ae2948c548d1'`

Tips:
- See https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/index.tsx#L203
- recentTags has type MediaWithTag [].  Apply the reducer function here.

**Comment by hawkishpolicy** [comment]
So I did a pair programming exercise with a fellow developer/climber....this is what we came up with:

```javascript
const fooTags = recentTagsByUsers.flatMap(entry => entry.mediaWithTags)
const recentTags = fooTags.filter(tag => {
    return !tag.entityTags.some(entityTag =>
      entityTag.targetId === '18c5dd5c-8186-50b6-8a60-ae2948c548d1'
    )
  })
 ```
  Is this a viable solution?
  
  Furthermore, is it worth considering altering the variables on the graphqlClient.query (line#88 api.ts) to exclude the Test Area  targetId?

**Comment by vnugent** [comment]
@hawkishpolicy yes, that's a great solution.  

> Furthermore, is it worth considering altering the variables on the graphqlClient.query (line#88 api.ts) to exclude the Test Area targetId?

We can define test area ID in an env variable because they are different in staging/development and production. 
I wouldn't add them to graphqlClient.query  because we do want test photos to show up when looking at the test page(s).

### Next.js env variable docs:
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#exposing-environment-variables-to-the-browser

Make sure to prefix the variable name with `NEXT_PUBLIC_`


Ps: in the future when including a code snippet, you can enclose them in 3 back ticks \`\`\`   ([GitHub docs: Formatting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code))

---

<img width="588" alt="Screenshot 2023-05-26 at 12 09 21 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/42ed33ea-54bf-49d0-94c8-c6921e25004b">

**Comment by hawkishpolicy** [comment]
I've been out of the loop doing contract work and family obligations.

I'll open this back up.

**Comment by vnugent** [comment]
Can you make test area IDs configurable? eg getting the values from .env file (see [Env vars in Next.js](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser))

Right now there's only 1 test area but I'm going to create another one in Australia/New Zealand so that we can test different grade systems.

Test areas:
In production:  ['18c5dd5c-8186-50b6-8a60-ae2948c548d1']

The main loop for showing media cards:  https://github.com/OpenBeta/open-tacos/blob/develop/src/components/home/RecentMedia.tsx#L15
